apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: validate
  name: validate
  namespace: webhook-channel
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: validate
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: validate
    spec:
      containers:
      - env:
        - name: TOKEN
          valueFrom:
            secretKeyRef:
              key: token
              name: sysdig-api-token
              optional: false
        image: srikantsarwa/webhook-channel:1
        imagePullPolicy: Always
        name: validate
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
